create sequence action_seq start with 1 increment by 50;
create sequence admin_job_log_seq start with 1 increment by 50;
create sequence admin_job_seq start with 1 increment by 50;
create sequence attributetype_seq start with 1 increment by 50;
create sequence category_seq start with 1 increment by 50;
create sequence config_seq start with 1 increment by 50;
create sequence context_seq start with 1 increment by 50;
create sequence dbuser_seq start with 1 increment by 50;
create sequence item_metadata_seq start with 1 increment by 50;
create sequence item_seq start with 1 increment by 50;
create sequence refresh_token_seq start with 1 increment by 50;
create sequence store_seq start with 1 increment by 50;
create sequence vw_context_seq start with 1 increment by 50;
create table action (action_id bigint not null, assignee_id bigint not null, completed_date timestamp(6), context_id bigint, creator_id bigint not null, date_archived timestamp(6), date_created timestamp(6), date_updated timestamp(6), due_date timestamp(6), item_id bigint, version bigint, uuid varchar(16) not null unique, external_action_tracker varchar(50) check (external_action_tracker in ('NONE','GOOGLE_TASKS','MICROSOFT_TODO','JIRA')), resolution varchar(1000), description varchar(255), external_etag varchar(255), external_id varchar(255), history json, icon varchar(255), name varchar(255) not null, priority varchar(255) not null check (priority in ('LOW','NORMAL','HIGH')), status varchar(255) not null check (status in ('OPEN','IN_PROGRESS','ON_HOLD','DONE','REJECTED')), primary key (action_id));
create table admin_job (end_time timestamp(6), id bigint not null, start_time timestamp(6), version bigint, configuration varchar(255), progress_info varchar(255), status varchar(255) check (status in ('QUEUED','RUNNING','COMPLETED','FAILED')), type varchar(255) check (type in ('INTEGRITY_CHECK','EXPORT_ARCHIVE','REINDEX_SEARCH')), primary key (id));
create table admin_job_log (id bigint not null, job_id bigint, timestamp timestamp(6), version bigint, message varchar(255), severity varchar(255), primary key (id));
create table attributetype (built_in boolean not null, data_type smallint not null check (data_type between 0 and 5), ordinal integer not null, attributetype_id bigint not null, date_archived timestamp(6), date_created timestamp(6), date_updated timestamp(6), version bigint, uuid varchar(16) not null unique, description varchar(255), icon varchar(255), name varchar(255) not null, primary key (attributetype_id));
create table category (object boolean, ordinal integer not null, category_id bigint not null, date_archived timestamp(6), date_created timestamp(6), date_updated timestamp(6), parent_category_id bigint, version bigint, uuid varchar(16) not null unique, description varchar(255), icon varchar(255), name varchar(255) not null, primary key (category_id), constraint UQ_CATEGORY_PARENT_NAME unique (parent_category_id, name));
create table config (config_id bigint not null, version bigint, config_key varchar(255), config_value varchar(255), primary key (config_id));
create table context (context_id bigint not null, date_archived timestamp(6), date_created timestamp(6), date_run_until timestamp(6), date_updated timestamp(6), version bigint, uuid varchar(16) not null unique, description varchar(255), icon varchar(255), name varchar(255) not null, stage varchar(255) not null check (stage in ('ACTIVE','CLOSED')), primary key (context_id));
create table context_category (category_id bigint not null, context_id bigint not null);
create table dbuser (date_archived timestamp(6), date_created timestamp(6), date_updated timestamp(6), user_id bigint not null, version bigint, uuid varchar(16) not null unique, description varchar(255), email varchar(255), firstname varchar(255), icon varchar(255), name varchar(255) not null, password varchar(255), preferences TEXT, saved_searches TEXT, user_role varchar(255) not null check (user_role in ('ADMIN','USER')), primary key (user_id));
create table item (text_parsed boolean not null, context_id bigint not null, date_archived timestamp(6), date_created timestamp(6), date_expire timestamp(6), date_updated timestamp(6), file_id bigint unique, issue_date timestamp(6), item_id bigint not null, store_id bigint, user_id bigint not null, version bigint, uuid varchar(16) not null unique, source varchar(20) check (source in ('UPLOAD','EMAIL','SCAN','API','UNKNOWN')), attributes json, description varchar(255), icon varchar(255), name varchar(255) not null, stage varchar(255) check (stage in ('ACTIVE','CLOSED')), storage_item_identifier varchar(255), constraint UNIQUE_ID primary key (item_id));
create table item_category (category_id bigint not null, item_id bigint not null);
create table item_metadata (file_id bigint not null, filesize bigint not null, crypt_settings varchar(255) not null, filename varchar(255) not null, mimetype varchar(255) not null, sha256_canonical varchar(255) not null unique, sha256crypted varchar(255) not null, sha256original varchar(255) not null unique, source varchar(255) not null, primary key (file_id));
create table refresh_token (expiry_date timestamp(6) with time zone not null, id bigint not null, user_id bigint not null, version bigint, token varchar(255) not null unique, primary key (id));
create table scheduled_tasks (consecutive_failures integer, picked boolean not null, priority smallint, execution_time timestamp(6) with time zone not null, last_failure timestamp(6) with time zone, last_heartbeat timestamp(6) with time zone, last_success timestamp(6) with time zone, version bigint not null, task_data bytea, picked_by varchar(255), task_instance varchar(255) not null, task_name varchar(255) not null, primary key (task_instance, task_name));
create table store (ordinal integer not null, date_archived timestamp(6), date_created timestamp(6), date_updated timestamp(6), store_id bigint not null, version bigint, uuid varchar(16) not null unique, description varchar(255), icon varchar(255), name varchar(255) not null, shortname varchar(255), primary key (store_id));
create index idx_action_uuid on action (uuid);
create index idx_action_assignee on action (assignee_id);
create index idx_action_status on action (status);
create index idx_action_duedate on action (due_date);
create index idx_attributetype_uuid on attributetype (uuid);
create index idx_category_uuid on category (uuid);
create index idx_category_parent_name on category (parent_category_id, name);
create index idx_config_key on config (config_key);
create index idx_context_uuid on context (uuid);
create index idx_context_dateArchived on context (date_archived);
create index idx_user_uuid on dbuser (uuid);
create index idx_item_uuid on item (uuid);
create index idx_item_issueDate on item (issue_date);
create index idx_item_dateArchived on item (date_archived);
create index idx_item_source on item (source);
create index idx_item_context on item (context_id);
create index idx_scheduled_tasks_execution_time on scheduled_tasks (execution_time);
create index idx_scheduled_tasks_last_heartbeat on scheduled_tasks (last_heartbeat);
create index idx_scheduled_tasks_priority_execution_time on scheduled_tasks (priority desc, execution_time asc);
create index idx_store_uuid on store (uuid);
alter table if exists action add constraint FK_ACTION_ASSIGNEE foreign key (assignee_id) references dbuser;
alter table if exists action add constraint FK_ACTION_CONTEXT foreign key (context_id) references context;
alter table if exists action add constraint FK_ACTION_CREATOR foreign key (creator_id) references dbuser;
alter table if exists action add constraint FK_ACTION_ITEM foreign key (item_id) references item;
alter table if exists admin_job_log add constraint FK_JOB_LOG_JOB foreign key (job_id) references admin_job;
alter table if exists category add constraint FK_CATEGORY_PARENT foreign key (parent_category_id) references category;
alter table if exists context_category add constraint FK_CTX_CAT_CATEGORY foreign key (category_id) references category;
alter table if exists item add constraint FK_ITEM_METADATA foreign key (file_id) references item_metadata;
alter table if exists item add constraint FK_ITEM_CONTEXT foreign key (context_id) references context;
alter table if exists item add constraint FK_ITEM_STORE foreign key (store_id) references store;
alter table if exists item add constraint FK_ITEM_USER foreign key (user_id) references dbuser;
alter table if exists item_category add constraint FK_ITEM_CAT_CATEGORY foreign key (category_id) references category;
alter table if exists item_category add constraint FK_ITEM_CAT_ITEM foreign key (item_id) references item;
alter table if exists refresh_token add constraint FKkffvel04rv5lgi00g0nvci74q foreign key (user_id) references dbuser;
